### ISSUE TITLE
ERC20 interaction 

### ISSUE THREAD

**Issue by reiven** [gnosis/MultiSigWallet#1]
Looks like Deposit event do no track ERC20 token deposits, normally such transactions use 0 ether

![image](https://user-images.githubusercontent.com/362717/29544851-5660daba-86c1-11e7-9317-2770aa595bcd.png)

Also, i want able to create a transaction which send a ERC20 transfer() as data
It is possible to transfer tokens with this contract?

**Comment by denisgranha** [comment]
in order to send transactions with your Multisig, you need to encode first the transaction you want to send, get the data field and call https://github.com/gnosis/MultiSigWallet/blob/master/contracts/MultiSigWallet.sol#L199

if you wanna avoid all this complexity, you can use the interface where you already can withdraw or deposit tokens https://wallet.gnosis.pm/#/wallets
Click on add > Recover > Paste you multisig address > Click on Multisig wallet 
In the tokens section, you can withdraw/deposit
