### ISSUE TITLE
cant send anymore

### ISSUE THREAD

**Issue by cristianizzo** [gnosis/MultiSigWallet#276]
<img width="1074" alt="Screenshot 2019-05-23 at 18 13 52" src="https://user-images.githubusercontent.com/5518760/58268858-8e6b5800-7d86-11e9-98c6-44b2d9104568.png">

**Comment by denisgranha** [comment]
what wallet are you using? take a screenshot of your setting plz

**Comment by cristianizzo** [comment]
Hi Denis, im using web wallet here the screenshot
<img width="1144" alt="Screenshot 2019-05-23 at 23 22 28" src="https://user-images.githubusercontent.com/5518760/58287606-c045e400-7db1-11e9-8618-f43b449acf1d.png">

**Comment by denisgranha** [comment]
did you update recently the ledger?

**Comment by cristianizzo** [comment]
yes, I have updated ledger firmware and coins app. 
I can try with the mac app

**Comment by cristianizzo** [comment]
i got a different issue on mac app trying to confirm a tx

<img width="1440" alt="Screenshot 2019-05-23 at 23 55 01" src="https://user-images.githubusercontent.com/5518760/58289273-3f3d1b80-7db6-11e9-8ae9-3ecdd4096941.png">

**Comment by giacomolicari** [comment]
Hi @cristianizzo ,
what's your Ledger's firmware version?

**Comment by cristianizzo** [comment]
Hi @giacomolicari it's the version 1.5.5

**Comment by denisgranha** [comment]
Hi Christian, 

So the problem here might be:

First, you don't have enabled in the ledger the option for browser and smart contract data.

Second option, I think ledger moved away from U2F and chrome deprecated another protocol that ledger uses in newer versions. I'm not sure about the solution, but I think Metamask might be able to solve your issue.

You can install metamask, https://metamask.io/ and then add connect the ledger in your metamask. 

<img width="310" alt="Screen Shot 2019-05-24 at 16 28 46" src="https://user-images.githubusercontent.com/4806080/58335067-1150e900-7e41-11e9-939d-64377822a46e.png">
<img width="442" alt="Screen Shot 2019-05-24 at 16 28 57" src="https://user-images.githubusercontent.com/4806080/58335070-157d0680-7e41-11e9-849b-49e25bbb0350.png">

Note there are two derivations, use legacy option.

Then, in your multisig options, use injected provider instead of ledger.

**Comment by cristianizzo** [comment]
it works with metamask, thanks :)

**Comment by denisgranha** [comment]
I’m glad it worked out!
