### ISSUE TITLE
The limit is not updated. Can't withdraw the money

### ISSUE THREAD

**Issue by MeLoco1** [gnosis/MultiSigWallet#35]
I'm testing mac os standalone version of the wallet if I can use it for business purpose. 
I created the multisig 2-of-3 contract, tx:
https://etherscan.io/tx/0x062304b0c7b54466aa71ebd530b4567af6c54fa106849a52c213f9be7a56d0a3

The limit is 0. I can't update the limit. I sent two txs to change the limit:
https://etherscan.io/tx/0xfdf2bf470b5f0e853ef196b17c459c95946971938bf1cdef0edbe21ab66d36fb
https://etherscan.io/tx/0xd4bb9e439c1fa8e9740b0edf34c851eb7c6e435abdabfa7896adbac2b6054194
both of them succeeded but the limit is still 0.
Furthermore I have 0.12 ETH on the main acc. Seems like 0.1 is the minimum needed to manipulate the contracts because if I have less the message `insufficient funds + gas` appears. 

Another question. Why the withdraw is not active? Is there any documentation for the wallet?

**Comment by denisgranha** [comment]
Hello @MeLoco1 in order to perform the transaction with the Multisig, the first step is correct:
1. [Submit Transaction](https://etherscan.io/tx/0xfdf2bf470b5f0e853ef196b17c459c95946971938bf1cdef0edbe21ab66d36fb)
2. You need to call confirmTransaction, not submitTransaction again

Withdraw with daily limit 0 was disabled in the main view, now is available on the last version
